# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sudo
email: brandonfujii2018@u.northwestern.edu
description: > # this means to ignore newlines until "baseurl:"
 Hi, I'm Brandon Fujii. I'm an LA native and a Computer Science student at Northwestern University. I love designing and developing for the web. Currently working on a mobile app @hearyeapp. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brandonfujii.com" # the base hostname & protocol for your site
twitter_username: brandonfujii
github_username:  brandonfujii

# Build settings
markdown: kramdown
